author: Alexander Hesse
name: TestPlugin
main: de.aquas_server.test.MyPlugin
version: 1.0
commands:
  jump:
    description: This is a jump command.
    usage: /jump location
    permission: TestPlugin.basic
    permission-message: You don't have permission.
  setjump:
    description: This is a setjump command.
    usage: /setjump location
    permission: TestPlugin.basic
    permission-message: You don't have permission.
  kistenfuellen:
    description: This is a kistenfuellen command.
    usage: /kistenfuellen world x1 y1 z1 x2 y2 z2
    permission: TestPlugin.basic
    permission-message: You don't have permission.